### PR TITLE
Disable trace output

### LINKED ISSUE #450: Want option to disable trace output files
The `run_glider` function unconditionally saves the stdout of the configured glider to `tracedir`. Depending on the glider being used, this can end up being a rather large amount of output, and frequent crashes can cause the tracedir to grow quite large.

The operator should be able to disable this functionality if it is causing issues or provides insufficient value.

### PR DESCRIPTION
**Pull request by esproul**
Fixes #450

### CODE REVIEW

File: src/utils/mtev_watchdog.c [hunk 1]
```diff
@@ -548,6 +555,7 @@ int mtev_watchdog_start_child(const char *app, int (*func)(void),
       sigaddset(&mysigs, SIGINT);
       setup_signals(&mysigs);
       mtev_monitored_child_pid = child_pid;
+      mtev_conf_get_boolean(MTEV_CONF_ROOT, "//watchdog/@save_trace_output", &save_trace_output);
```
Comment (postwait) [inline src/utils/mtev_watchdog.c]: we should not use mtev_conf from with utils/

We need to expose a function to set that boolean and call it from mtev_main.c dependent upon this config value

Comment (esproul) [reply src/utils/mtev_watchdog.c]: Addressed in latest commit.
